### ISSUE TITLE
SERVICE_DISABLED error when using the library

### ISSUE THREAD

**Issue by abouda** [stevdza-san/OneTapCompose#3]
Hi!
I got an error message while trying out the lib. I have done the steps with app sha1 and web client id.
Do you by any chance know what could be wrong.

`com.google.android.gms.persistent    E  [GoogleAccountDataServiceImpl] getToken() -> SERVICE_DISABLED. App: com.elab.testgoog, Service: oauth2:openid
                                                                                                    zpc: Service not whitelisted
                                                                                                    	at ley.l(:com.google.android.gms@230514044@23.05.14 (190400-509319212):57)
                                                                                                    	at ovz.i(:com.google.android.gms@230514044@23.05.14 (190400-509319212):2)
                                                                                                    	at ovz.eo(:com.google.android.gms@230514044@23.05.14 (190400-509319212):115)
                                                                                                    	at gma.onTransact(:com.google.android.gms@230514044@23.05.14 (190400-509319212):5)
                                                                                                    	at android.os.Binder.transact(Binder.java:1200)
                                                                                                    	at arzy.onTransact(:com.google.android.gms@230514044@23.05.14 (190400-509319212):1)
                                                                                                    	at android.os.Binder.transact(Binder.java:1200)
                                                                                                    	at amdf.onTransact(:com.google.android.gms@230514044@23.05.14 (190400-509319212):21)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1316)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1280)`

**Comment by stevdza-san** [comment]
You need to make sure that you're device has Google Play Services SDK enabled (If you're using an emulator). Have you tried it with a real android smartphone device?

**Comment by abouda** [comment]
Yes I am running the app on a real device. I even created a new empty app from scratch to test. Same issue.
I get that error stack trace and then your error message "Google Account not Found."
I can try testing on other devices.

**Comment by stevdza-san** [comment]
You need to double check whether you have the correct client_id in your Android Studio. You need to use WEB client ID from your project on Google Cloud Platform. Also be sure to add the correct SHA-1 and package name of you project, in your ANDROID client on GCP as well. One my device, everything works fine, I've just tested it again.

**Comment by abouda** [comment]
I tested on 5 other devices and it works fine. Just doesn't work on my main device :/
So it must be device related. I'm not sure what the issue is but I'll look into it.
Thanks for the quick replies.
